### ISSUE TITLE
defaultOffsetPct value ignored

### ISSUE THREAD

**Issue by mjcampagna** [mhayes/twentytwenty#2]
Hi,

defaultOffsetPct value is being ignored for the slider in the jQuery version; the value does get used for the portions of each image being shown. So the portions of the image and the slider position do not match on load.

Not sure about Angular, as I'm not using it.

Cheers,
Matt

**Comment by mhayes** [comment]
Confirmed this issue as well, I'll try to get a patch out shortly.

**Comment by mhayes** [comment]
Just pushed out a new release that appears to fix the issue you're running into:

https://github.com/mhayes/twentytwenty/releases/tag/v2.0.0-beta.1

Cheers!
